### PR TITLE
Adds option to pages not showing files in side panel

### PR DESCRIPTION
**Pull request by Tschuppi81**
Org: Per page option to switch off showing files in the sidebar

TYPE: Feature
LINK: ogc-1477

## Checklist

- [ ] I have performed a self-review of my code
- [x] I considered adding a reviewer
- [x] I have updated the PO files
- [ ] I made changes/features for both org and town6
- [ ] I have tested my code thoroughly by hand
    - [ ] I have tested styling changes/features on different browsers
    - [ ] I have tested javascript changes/features on different browsers
    - [ ] I have tested database upgrades
    - [ ] I have tested sending mails
    - [ ] I have tested building the documentation
- [ ] I have added tests for my changes/features
    - [ ] I am using freezegun for tests depending on date and times
    - [ ] I considered using browser tests für javascript changes/features
    - [ ] I have added/updated jest tests for d3rendering (election_day, swissvotes)

### CODE REVIEW

**Comment by Tschuppi81** [comment]
@BreathingFlesh I have the issue the option works like a charm for org where as in town6 files are not shown although my printouts in the template show files are present. Any idea what I do wrong in the template condition for town6?

**Comment by BreathingFlesh** [comment]
I can see them without a problem in both org and town6. Are you sure you haven't unchecked your new checkbox for hiding the files?

**Comment by BreathingFlesh** [comment]
> @BreathingFlesh I have the issue the option works like a charm for org where as in town6 files are not shown although my printouts in the template show files are present. Any idea what I do wrong in the template condition for town6?

I can see them without a problem in both org and town6. Are you sure you haven't unchecked your new checkbox for hiding the files?

**Comment by Tschuppi81** [comment]
Indeed, I verified now for Ebikon and Ottenbach. I used Meggen for development and now I remember it is manually disabled in css...

**Pull request merged**
