### PR TITLE
Fixme Makes the xml export generic

### PR DESCRIPTION
**Pull request by Tschuppi81**
Export: Implement a generic xml export

TYPE: Bugfix
LINK: None | Fixme

### CODE REVIEW

**Comment by Tschuppi81** [comment]
Replaces the obscure occurrence xml export (I did earlier) with a generic implementation. Tested for event export and newsletter recipients

**Comment by Tschuppi81** [comment]
@Daverball Do I need to implement stubs for 'dicttoxml' to fix the mypy errors?

**Comment by Daverball** [comment]
It's probably good enough to just add `type:ignore[import-untyped]` to the import for now. Not sure whether it's worth adding stubs for this one function.

**Review by Daverball — APPROVED** [review]
Since you wrote the original XML export I assume the original use-case is still supported after this change and provides equivalent functionality.

**Comment by Tschuppi81** [comment]
> Since you wrote the original XML export I assume the original use-case is still supported after this change and provides equivalent functionality.

Yes, it was for the event export :+1:

**Comment by Tschuppi81** [comment]
grrr, mis-clicked resulting in a bad commit message...

**Pull request merged**
