### PR TITLE
Election Day: Adds cli util to extract the mapping

### PR DESCRIPTION
**Pull request by cyrillkuettel**
## Commit message

Election Day: Adds cli util to extract the mapping

TYPE: Feature
LINK: OGC-1354

## Checklist

- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by msom** [comment]
Why not just include our internal ID to the export?

**Comment by cyrillkuettel** [comment]
> Why not just include our internal ID to the export?

I would love to. However this would create very long filenames for some cases.

Or do you mean separate? Yes we should do that. Best would be if the filenames and urls have 1:1 relationship.

**Comment by msom** [comment]
No I mean add the ID to the into the file content. I will add this for votes, elections and compounds....

**Comment by cyrillkuettel** [comment]
Closing this because we'll add it as a column

**Pull request closed without merging**
