### PR TITLE
Feature/ogc 1337 file icon replacing file extension

### PR DESCRIPTION
**Pull request by Tschuppi81**
org/town6: Replace file extension with icon and tooltip

TYPE: Feature
LINK: ogc-1337

## Checklist

- [x] I have performed a self-review of my code
- [x] I considered adding a reviewer
- [x] I made changes/features for both org and town6

### CODE REVIEW

**Comment by Tschuppi81** [comment]
@BreathingFlesh I need your review and support on css in general as well as on the ::after which I don't manage to get rid of.
Screenshot from 2023-11-21 12-52-29

How to reproduce:
 - go to any topic page e.g. http://localhost:8080/onegov_town6/ebikon/topics/leben-wohnen
 - edit the page
 - add a file (at the end of the form) and submit
 - the file panel is visible on the right, right above 'Personen'

**Comment by Tschuppi81** [comment]
Now I figured out the issue!

**Review by BreathingFlesh — CHANGES_REQUESTED** [review]
The rest looks good.

**Comment by Tschuppi81** [comment]
It works out nicely with the csv icon
image

**Pull request merged**
